### ISSUE TITLE
Build failed when there are no entities folder

### ISSUE THREAD

**Issue by syedmwma** [cisco/mindmeld#12]
Steps to reproduce:

1. Create a new mindmeld blueprint
2. Add a new intent (e.g domains\food_ordering\greet\train.txt) and populate with training data
3. Build the blueprint. It should be building as expected
4. Delete the entities folder
5. Build the blueprint. It should be failing with unhandled exception

How I found this out is I create a new blueprint, put my intent and put it inside the git repository. As git doesnt push empty folders, when I pull my source into another server, the build failed.

mindmeld) syed@ubuntu:~/mindmeld$ python -m appspace-app build
/home/syed/mindmeld/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
Numerical parser running, PID 9400
/home/syed/mindmeld/lib/python3.6/site-packages/mindmeld/_version.py:64: MindMeldVersionWarning: Current mindmeld (4.1.1) does not satisfy mindmeld==4.1.0 in pip requirements caused by (mindmeld 4.1.1 (/home/syed/mindmeld/lib/python3.6/site-packages), Requirement.parse('mindmeld==4.1.0'))
  warnings.warn(error_msg, category=MindMeldVersionWarning)
warning: The application package appspace-app is already imported.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/syed/mindmeld/appspace-app/__main__.py", line 8, in <module>
    app.cli()
  File "/home/syed/mindmeld/lib/python3.6/site-packages/mindmeld/app.py", line 166, in cli
    app_cli(obj={'app': self})
  File "/home/syed/mindmeld/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/syed/mindmeld/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/syed/mindmeld/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/syed/mindmeld/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/syed/mindmeld/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/syed/mindmeld/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/syed/mindmeld/lib/python3.6/site-packages/mindmeld/cli.py", line 163, in build
    app.lazy_init()
  File "/home/syed/mindmeld/lib/python3.6/site-packages/mindmeld/app.py", line 79, in lazy_init
    async_mode=self.async_mode)
  File "/home/syed/mindmeld/lib/python3.6/site-packages/mindmeld/app_manager.py", line 89, in __init__
    self.nlp = nlp or NaturalLanguageProcessor(app_path, resource_loader)
  File "/home/syed/mindmeld/lib/python3.6/site-packages/mindmeld/components/nlp.py", line 360, in __init__
    self._children[domain] = DomainProcessor(app_path, domain, self.resource_loader)
  File "/home/syed/mindmeld/lib/python3.6/site-packages/mindmeld/components/nlp.py", line 640, in __init__
    self.resource_loader)
  File "/home/syed/mindmeld/lib/python3.6/site-packages/mindmeld/components/nlp.py", line 823, in __init__
    self.parser = Parser(self.resource_loader, domain=domain, intent=intent)
  File "/home/syed/mindmeld/lib/python3.6/site-packages/mindmeld/components/parser.py", line 74, in __init__
    entity_types = path.get_entity_types(app_path) + ['unk']
  File "/home/syed/mindmeld/lib/python3.6/site-packages/mindmeld/path.py", line 238, in get_entity_types
    return next(os.walk(entities_dir))[1]
StopIteration
(mindmeld) syed@ubuntu:~/mindmeld$

**Comment by minhtuev** [comment]
Closing this issue since we will not address for now.
