### ISSUE TITLE
Backward incompatibility for entity recognition in mindmeld

### ISSUE THREAD

**Issue by jimilpatel24** [cisco/mindmeld#208]
When you load the bots built in the pre-4.3 release (4.2.10 for example), we see the below error. The error is related to a change in the EntityLabelEncoder class, where you added self.system_entity_recognizer = SystemEntityRecognizer.get_instance(). This causes old apps to fail since they don't have the field.

Error: **EntityLabelEncoder** object has no attribute **system_entity_recognizer**

**Comment by minhtuev** [comment]
Reopening this issue since we continue to observe this error.

I am able to reproduce with the kwik-e-mart blueprint for building MM4.2.11 and running with MM4.3.1:
```
Fitting entity recognizer: domain='store_info', intent='greet'
There are no labels in this label set, so we don't fit the model.
Fitting entity recognizer: domain='store_info', intent='help'
There are no labels in this label set, so we don't fit the model.
Fitting entity recognizer: domain='store_info', intent='exit'
There are no labels in this label set, so we don't fit the model.
Fitting entity recognizer: domain='store_info', intent='find_nearest_store'
There are no labels in this label set, so we don't fit the model.
Saving intent classifier: domain='store_info'
Saving entity classifier: domain='store_info', intent='get_store_hours'
Saving role classifier: domain='store_info', intent='get_store_hours', entity='sys_time'
Saving role classifier: domain='store_info', intent='get_store_hours', entity='store_name'
Saving entity classifier: domain='store_info', intent='greet'
Saving entity classifier: domain='store_info', intent='help'
Saving entity classifier: domain='store_info', intent='exit'
Saving entity classifier: domain='store_info', intent='find_nearest_store'
(mm42) ➜  blueprints git:(master) ✗ cd ..
(mm42) ➜  mindmeld-blueprints git:(master) ✗ cd blueprints
(mm42) ➜  blueprints git:(master) ✗ conda deactivate
(base) ➜  blueprints git:(master) ✗ conda activate mm43
(mm43) ➜  blueprints git:(master) ✗ ls
banking_blueprint food_ordering     home_assistant    hr_assistant      kwik_e_mart       log               template          video_discovery
(mm43) ➜  blueprints git:(master) ✗ python -m kwik_e_mart converse
/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
Numerical parser running, PID 37205
warning: The application package kwik_e_mart is already imported.
No question_answering model configuration set. Using default.
Loading intent classifier: domain='store_info'
Loading entity recognizer: domain='store_info', intent='greet'
Loading entity recognizer: domain='store_info', intent='get_store_hours'
No entity_resolution model configuration set. Using default.
warning: Entity data file not found at '/Users/minhtue/workspace/mindmeld-blueprints/blueprints/kwik_e_mart/entities/sys_time/gazetteer.txt'. Proceeding with empty entity data.
warning: Entity mapping file not found at '/Users/minhtue/workspace/mindmeld-blueprints/blueprints/kwik_e_mart/entities/sys_time/mapping.json'. Proceeding with empty entity data.
warning: Entity map file not found at /Users/minhtue/workspace/mindmeld-blueprints/blueprints/kwik_e_mart/entities/sys_time/mapping.json
No entity_resolution model configuration set. Using default.
Loading role classifier: domain='store_info', intent='get_store_hours', entity_type='sys_time'
Loading role classifier: domain='store_info', intent='get_store_hours', entity_type='store_name'
Loading entity recognizer: domain='store_info', intent='exit'
Loading entity recognizer: domain='store_info', intent='help'
Loading entity recognizer: domain='store_info', intent='find_nearest_store'
You: hi
/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
App: Hello. I can help you find store hours for your local Kwik-E-Mart. How can I help?
...  Listening...
You: When does the Elm Street store close
Traceback (most recent call last):
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/minhtue/workspace/mindmeld-blueprints/blueprints/kwik_e_mart/__main__.py", line 8, in <module>
    app.cli()
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/mindmeld/app.py", line 241, in cli
    app_cli(obj={"app": self})
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/mindmeld/cli.py", line 149, in converse
    responses = convo.say(message)
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/mindmeld/components/dialogue.py", line 1315, in say
    response = self.process(text, params=params)
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/mindmeld/components/dialogue.py", line 1383, in process
    verbose=self.verbose,
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/mindmeld/app_manager.py", line 200, in parse
    query_text=text, allowed_intents=allowed_intents, **nlp_params
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/mindmeld/components/nlp.py", line 744, in process
    verbose=verbose,
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/mindmeld/components/nlp.py", line 277, in process
    query, allowed_nlp_classes, dynamic_resource, verbose
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/mindmeld/components/nlp.py", line 593, in process_query
    query, allowed_intents, dynamic_resource=dynamic_resource, verbose=verbose
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/mindmeld/components/nlp.py", line 953, in process_query
    query, dynamic_resource=dynamic_resource, verbose=verbose
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/mindmeld/components/nlp.py", line 1318, in process_query
    query, dynamic_resource=dynamic_resource, verbose=verbose
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/mindmeld/components/nlp.py", line 1282, in _get_pred_entities
    query, dynamic_resource=dynamic_resource, verbose=verbose
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/mindmeld/components/nlp.py", line 1155, in _recognize_entities
    **{"dynamic_resource": dynamic_resource, "verbose": verbose}
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/mindmeld/components/nlp.py", line 338, in _process_list
    return tuple([getattr(self, func)(itm, *args, **kwargs) for itm in items])
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/mindmeld/components/nlp.py", line 338, in <listcomp>
    return tuple([getattr(self, func)(itm, *args, **kwargs) for itm in items])
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/mindmeld/components/nlp.py", line 1177, in _recognize_entities
    query, dynamic_resource=dynamic_resource
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/mindmeld/components/entity_recognizer.py", line 228, in predict
    dynamic_resource=dynamic_resource,
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/mindmeld/components/classifier.py", line 273, in predict
    return self._model.predict([query], dynamic_resource=dynamic_resource)[0]
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/mindmeld/models/tagger_models.py", line 232, in predict
    for example_predicted_tags, example in zip(predicted_tags, examples)
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/mindmeld/models/tagger_models.py", line 232, in <listcomp>
    for example_predicted_tags, example in zip(predicted_tags, examples)
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/mindmeld/models/model.py", line 1301, in decode
    for idx, tags in enumerate(tags_by_example)
  File "/Users/minhtue/opt/anaconda3/envs/mm43/lib/python3.6/site-packages/mindmeld/models/model.py", line 1301, in <listcomp>
    for idx, tags in enumerate(tags_by_example)
AttributeError: 'EntityLabelEncoder' object has no attribute 'system_entity_recognizer

**Comment by minhtuev** [comment]
Verified that the existing bugfix should work.
